# Generated by Django 5.2 on 2025-06-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=150)),
                ('fecha_adquisicion', models.DateField()),
                ('imagen', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
