# Generated by Django 5.2 on 2025-06-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Impresoras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresora',
            name='fecha_adquisicion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='impresora',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='impresora',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='impresoras'),
        ),
    ]
