# Generated by Django 5.2 on 2025-06-09 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Impresoras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantenimiento', models.DateField()),
                ('tecnico', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
                ('informe_pdf', models.BinaryField(blank=True, null=True)),
                ('impresora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Impresoras.impresora')),
            ],
        ),
    ]
